#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/capstone_project?characterEncoding=UTF-8
#    username: root
#    password: root
#  mvc:
#    static-path-pattern: /static/**
#    view:
#       prefix: /WEB-INF/jsp/
#       suffix: .jsp
#       prefix: templates/
#       suffix: .js
#server:
#  port: 80
  
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cvyoreexeqln.us-east-2.rds.amazonaws.com:3306/capstone_project?characterEncoding=UTF-8
    username: root
    password: capstone
  mvc:
    static-path-pattern: /static/**
    view:
       prefix: /WEB-INF/jsp/
       suffix: .jsp
#       prefix: templates/
#       suffix: .js
server:
  port: 80