spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c7rig0vgsupo.ap-northeast-2.rds.amazonaws.com:3306/capstone_project?characterEncoding=UTF-8
    username: root
    password: capstone
  mvc:
    static-path-pattern: /static/**
    view:
       prefix: /WEB-INF/jsp/
       suffix: .jsp
#       prefix: templates/
#       suffix: .js
server:
  port: 8080